//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MIIEowIBAAKCAQEA2WbzJ5xS3TGee1zi/VncN8o+HqTshTZnufagc7PUr3hCpj9BSe5gWGnsU45gRB8q3Kf5bP20U280dySVT5Wwkb6iC7XAivfgogbQtQ0ZpR0GNrqhU5Ly3FxN1a+or3LlcswX8LahpeOSszpySM7/WAvAFIzzVQOXQ3aN/RBU0vR2lnxDA25qeNi9mS4M8IjWqKcl09rdSwSumkuZs6NC8NvKYxVTePR8Oo/vf7H1bgXNakgMvGKC82s/+5Iks2z2EzPxL+XRhj6GNp4TZ9ECVp79HHNcdoUu0GuW9OQCRBxB9WcCrm3VtoEUwtOqkvTkNxOg5t47tEB/K5r2l7ac0QIDAQABAoIBABTpcjo9LztXqobzSGJWYnh7W75W3ulxckjREF4QzkSSrNaQ/xa9d0cJ6VGgQGJNHTJcdgGl5dKgv8s2GaauH23liHDX6s1zSohLX4gK2oynXhGloh8H45SOzG3hl7hItQl12FevOZ1bZqEW [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string private_key {
            get {
                return ResourceManager.GetString("private_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgHYQRGbs8AWe2HFnMVES/wCir0WnVdkT7/gHOforPvatqjyENedLDyNAjXJYIM8OSBknurbD+BNQ2fp5u3us8WjG3juN7gjUKhpwuzO7UgBHjYye1g04LVVUJRdkIMyjI43CQorFpJO+cfR7ctUl6ArA9n+/CSmLTLSMRw3Qax+W2n6sR0P9jsTOFu21uWVfkaLcPQQnfxKQdUKmAQKMFUX5YeqR064M74YosRJjvs/5UVmfOuU6rRKpVKg5L6OK1MxEc0RIVG0Lxd1fVABAyzP2CXk+2r3FP7wajdfzOZVBwOo6x6CH64dKif1u9wyhPEwrKmP5uwp0dOK/S6hxVwIDAQAB 的本地化字符串。
        /// </summary>
        internal static string public_key {
            get {
                return ResourceManager.GetString("public_key", resourceCulture);
            }
        }
    }
}
